// Categorias

export const GET_CATEGORIA_SUCCESS = "GET_CATEGORIA_SUCCESS";
export const GET_CATEGORIA_FAIL = "GET_CATEGORIA_FAIL";

// Sub-Categorias
export const GET_SUB_CATEGORIA_SUCCESS = "GET_SUB_CATEGORIA_SUCCESS";
export const GET_SUB_CATEGORIA_FAIL = "GET_SUB_CATEGORIA_FAIL";

// Producto

export const GET_PRODUCTO_SUCCESS = "GET_PRODUCTO_SUCCESS";
export const GET_PRODUCTO_FAIL = "GET_PRODUCTO_FAIL";

// Proveedor
export const GET_PROVEEDOR_SUCCESS = "GET_PROVEEDOR_SUCCESS";
export const GET_PROVEEDOR_FAIL = "GET_PROVEEDOR_FAIL";

// Cliente
export const GET_CLIENTE_SUCCESS = "GET_CLIENTE_SUCCESS";
export const GET_CLIENTE_FAIL = "GET_CLIENTE_FAIL";
