# Generated by Django 4.0.6 on 2022-09-25 22:27

import apps.inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventario.models.img_directory_path),
        ),
    ]
