# Generated by Django 4.0.6 on 2022-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('Seleccion Una Opcion:', 'Seleccion Una Opcion:'), ('Natural', 'Natural'), ('Jurídico', 'Juridica'), ('Extranjero', 'Extranjero')], default='Seleccion Una Opcion:', max_length=25),
        ),
    ]
